### ISSUE TITLE
Provide the Android application to work with for not programmers

### ISSUE THREAD

**Issue by psielicka** [KristiSik/TSD-PokerPlanning#37]
Provide the Android application to work with for not programmers.

AC1: It have to be usable by not only developers
AC2: It have to be working application

**Comment by psielicka** [comment]
It is going to be working app on browser in https://appetize.io/ system

**Comment by bardss** [comment]
Everything done. 
Link added to project readme.
Application can be check on:
https://appetize.io/app/m0063xebg1jzjpy2kkrafe32gm?device=nexus5&scale=75&orientation=portrait&osVersion=7.1
Application executable file (.apk) can be also downloaded from project and opened on private phone.
