### ISSUE TITLE
User send information that he is ready to finish a game

### ISSUE THREAD

**Issue by psielicka** [KristiSik/TSD-PokerPlanning#59]
After choosing a card user needs to send an information to the server that he is ready to finish a game and see results.

AC1: User can send an information that he is ready by turning the switch to "ON" position

AC2: After sending "ready" information user can change his status to "not ready yet" by turning the switch back to "OFF" position.

AC3: After turning the switch back to "off" position user can select different card.

**Comment by paulinaaniola** [comment]
All done
