### ISSUE TITLE
Write application requirements

### ISSUE THREAD

**Issue by bardss** [KristiSik/TSD-PokerPlanning#72]
Application have to have written requirements to check if everything is working as planned.

AC1: Requirements have to be achievable
AC2: Requirements have to be clear to interpret them in application

**Comment by paulinaaniola** [comment]
Application requirements.

Main goal of EstimateIT! application is to provide environment for people working in groups to estimate tasks in convenient way. 

1. Functionalities:
- creating a room for users
- joining room
- room owner set estimation topic
- room owner starts estimation
- room participants can choose card (Fibonacci number)
- checking results of estimation
- multiple estimations in one room
- room owner can kick participant

2. Security
- user can register account in application views
- user can log in in account (application is not saving password)
- server access based on user login token, not on private credentials
- application local database is only saving the user email for convenient login process

3. Accessibility 
- application working on smartphones with Android version 5.0+
- application working on tablets with Android version 5.0+

4. Backend Server
- minimum 1GB of RAM
- minimum 30 GB of HDD or SSD
- running on Windows Server 2012 R2 or later
- .NET Core 2.0 or later
- Microsoft SQL Server 2012 or later
- server IP (v4) is accessible from the Internet or company network

**Comment by paulinaaniola** [comment]
All done
